---
name: Lint the generated project
on: [push]  # yamllint disable-line rule:truthy

jobs:
  lint-generated:
    name: Lint the generated project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip3 install -r requirements.txt
      - run: |
          copier . test-project \
          --defaults \
          -d project_name="Template Test" \
          -d project_description="The description of a template test." \
          -d author_name="Continuous Integration" \
          -d author_email="test@ci.com" \
          -d author_username="ci"
      - name: lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: test-project
          # yamllint disable rule:indentation
          config_data: |
            extends: default
            rules:
              indentation:
                spaces: 2
                check-multi-line-strings: true
              quoted-strings:
                quote-type: double
                required: only-when-needed
              line-length:
                max: 88
            ignore-from-file: test-project/.gitignore
          # yamllint enable rule:indentation
