---
name: Lint self
on: [push]

jobs:
  lint-self:
    name: Lint self
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          # yamllint disable rule:indentation
          config_data: |
            extends: default
            rules:
              indentation:
                spaces: 2
                check-multi-line-strings: true
              quoted-strings:
                quote-type: double
                required: only-when-needed
              line-length:
                max: 88
              truthy:
                ignore:
                  - .github/workflows/*
            ignore:
              - template/
          # yamllint enable rule:indentation
      - name: lint workflows
        # yamllint disable rule:line-length
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        # yamllint enable rule:line-length
        shell: bash
