---
name: Lint self
on: [push]  # yamllint disable-line rule:truthy

jobs:
  lint-self:
    name: Lint self
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: lint YAML
        uses: ibiqlik/action-yamllint@v3
