---
name: Lint self
on: [push]

jobs:
  lint-self:
    name: Lint self
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: lint self
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .template/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
