---
name: Lint the generated project
on: [push]

jobs:
  lint-generated:
    name: Lint the generated project
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - run: pip3 install -r requirements.txt
      - run: |
          copier . acme-project \
          --defaults \
          -d project_name="Project ACME" \
          -d project_description="The description of the ACME project." \
          -d author_name="American Company" \
          -d author_email="boom@acme.com" \
          -d author_username="acme"
      - name: create lockfile
        run: pdm lock
        working-directory: acme-project
      - name: lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: acme-project
          # yamllint disable rule:indentation
          config_data: |
            extends: default
            rules:
              indentation:
                spaces: 2
                check-multi-line-strings: true
              quoted-strings:
                quote-type: double
                required: only-when-needed
              line-length:
                max: 88
              truthy:
                ignore:
                  - acme-project/.github/workflows/*
            ignore:
              - acme-project/.copier-answers.yml
          # yamllint enable rule:indentation
      - name: check black conformity
        uses: psf/black@stable
        with:
          src: acme-project
      - name: validate noxfile
        run: nox --list
        working-directory: acme-project
